### ISSUE TITLE
[PowerShell/en]: A statement is missing.

### ISSUE THREAD

**Issue by Laoujin** [adambard/learnxinyminutes-docs#2095]
In the source code:
https://github.com/adambard/learnxinyminutes-docs/pull/2039/files
on line 244-245:

```
# Syntax for calling static .NET methods
[System.Reflection.Assembly]::LoadWithPartialName('Microsoft.VisualBasic')
```

For some reason, the second line has been parsed out of the HTML page.

**Comment by Oire** [comment]
@Laoujin, is this fixed now?

**Comment by Laoujin** [comment]
Nope, it still doesn't show up in https://learnxinyminutes.com/docs/powershell/

**Comment by Oire** [comment]
Hm. For some reason, it seems to think it is Markdown, not code (since there are brackets and then parenthesis). @adambard, any ideas, please?

**Comment by divayprakash** [comment]
Fixed in 67e2ff0.
