### ISSUE TITLE
elixir/sk is a 404 not found

### ISSUE THREAD

**Issue by peterszatmary** [adambard/learnxinyminutes-docs#2536]
My pull request ( [#2466](https://github.com/adambard/learnxinyminutes-docs/pull/2466) ) was merged a few days ago. But pages [https://learnxinyminutes.com/docs/sk-sk/elixir/](https://learnxinyminutes.com/docs/sk-sk/elixir/) doesnt work properly. 404 not found. If is there something that i did wrong please let me know. I will fix it. Thanks in advance.

**Comment by vendethiel** [comment]
This one time's not my fault! Should be fixed now :-).

**Comment by peterszatmary** [comment]
Still not working. See please [https://learnxinyminutes.com/docs/sk-sk/elixir/](https://learnxinyminutes.com/docs/sk-sk/elixir/)

**Comment by samcv** [comment]
Fixed by adambard/learnxinyminutes-site#36 . Site's SSL cert is out of date atm but the page is generating fine now.
